name: CI/CD with Semantic Release

on:
  push:
    branches:
      - main
      - staging

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  staging:
    name: Deploy to Vercel (Staging)
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./
          alias-domains: ci-cd-automation.vercel.app

  # production:
  #   name: Deploy to Render (Production)
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - run: npm ci

  #     # 🔢 Semantic Release
  #     - name: Semantic Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: npx semantic-release

  #     # 🐳 Docker Build
  #     - name: Log in to GitHub Container Registry
  #       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     - name: Build and Push Docker image
  #       run: |
  #         docker build -f Dockerfile -t ghcr.io/${{ github.repository }}:latest .
  #         docker push ghcr.io/${{ github.repository }}:latest

  #     # 🚀 Deploy to Render
  #     - name: Trigger Deploy on Render
  #       run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
